### ISSUE TITLE
Assigned User with LDAP is null

### ISSUE THREAD

**Issue by Virtute90** [espocrm/espocrm#2363] opened 2022-07-05 07:25 UTC
**Describe the bug**
The value of assigned user with the authentication LDAP is always null

**To Reproduce**
1. Configure the ldap authentication 
2. Sign in with the user with /portal
3. Go to contacts or any other category
4. The filed assigned user is none 

**Expected behavior**
The filed assigned it should be the session user

**Screenshots**
Calls
![image](https://user-images.githubusercontent.com/32056724/177271682-b06c6eab-b04e-4ff1-bfee-bbf3eaee2021.png)
Contacts
![image](https://user-images.githubusercontent.com/32056724/177271765-250fd2ea-b560-4e5b-b079-4f2c540005cd.png)

**EspoCRM version**
I installed espocrm with the dockers and updated it to the latest version 7.1.9 today

**Additional context**
If I add a call from the dashboard with the "+" key, the assigned user is displayed correctly but when entering the data this error is returned:
Error 400: Bad request
Not valid data. Field: assignedUser, validation type: required
![image](https://user-images.githubusercontent.com/32056724/177272330-f11c09a0-1f6f-4964-8adc-fefbe4807c15.png)

**Comment by yurikuzn** [comment] 2022-07-05 07:52
If you disable the LDAP authentication type it works OK?

**Comment by yurikuzn** [comment] 2022-07-05 07:56
I suspect that this has nothing to do with LDAP. The problem is the Assigned User field is mandatory. But a portal user is not permitted to assign records by a design (neither assign to self). You can disable *Required* in Administration > Entity Manager > Call > Fields > Assigned User, or fill assigned user with a formula.

**Comment by yurikuzn** [comment] 2022-07-05 08:27
> The filed assigned it should be the session user.

This is not valid for portal users.

**Comment by Virtute90** [comment] 2022-07-05 08:28
> I suspect that this has nothing to do with LDAP. The problem is the Assigned User field is mandatory. But a portal user is not permitted to assign records by design (neither assign to self). You can disable the _Required_ parameter at Administration > Entity Manager > Call > Fields > Assigned User, or fill the assigned user field with a formula, by setting some existing user.

I know I can set it as non-mandatory but I would like the field to populate correctly so I know who entered the information.
I try to do some tests with the formulas, let's see if I can solve the problem.
Thank you

**Closed by yurikuzn** 2022-07-05 08:27 UTC

**Comment by Virtute90** [comment] 2022-07-05 08:36
> This is how it was designed. Portal user never can be an assigned user, this is logical from the business perspective. You have the Created By field to know who created.

Thanks, I solved it this way
