### ISSUE TITLE
entryPoint=changePassword is not available on custom portal URL's

### ISSUE THREAD

**Issue by wimjaap** [espocrm/espocrm#2820] opened 2023-08-08 15:57 UTC
**Describe the bug**
When using a custom portal URL such as https://portal.domain.com and a CRM on https://crm.domain.com a password change request for a portal user sends a URL like this: https://portal.domain.com/?entryPoint=changePassword&id=XXXX
This returns a 404 not found. If I replace the domain part with "crm.domain.com" it works, but I don't want portal users to access that URL.

**To Reproduce**
Explicit steps to reproduce the behavior:
1. Follow the guide on custom portal URL's
2. Followed the Nginx configuration for custom portal domains
3. Reset a portal user password from the admin interface
4. User gets an email with a non-working URL
...

**Expected behavior**
I expect the user gets a password reset page instead of a 404 error.

**Screenshots**

**EspoCRM version**
7.5.5

**Comment by yurikuzn** [comment] 2023-08-08 16:59
We've been using this feature for the portal and it always worked.

**Comment by yurikuzn** [comment] 2023-08-08 17:02
I believe we've been using this feature for many years and it always worked. Might need to configure your webserver to make ` https://portal.domain.com/?entryPoint=changePassword&id=XXXX` to work.

**Comment by yurikuzn** [comment] 2023-08-08 17:05
Closing it likely not a bug in the product but likely a configuration issue.

**Closed by yurikuzn** 2023-08-08 17:05 UTC

**Comment by yurikuzn** [comment] 2023-08-15 16:16
This fix may solve the problem: https://github.com/espocrm/espocrm/commit/3c64db25b9ebda27ac59738c18472c97cac4f69f

**Comment by wimjaap** [comment] 2023-08-15 22:01
Thanks, I'm not able to test right now, as due to this issue I decided to just run Keycloak and have Portal users authenticate using OIDC. Which also allows them to just have one account for both my frontend and portal. Pretty nice that actually works very well! 👍
