### ISSUE TITLE
Emails from Gmail are being redownloaded after awhile. 

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#1516] opened 2019-11-19 18:36 UTC
The emails from Gmail, that are already on the system, are being re-downloaded after some time, with a different Unique ID. We are having a lot of duplicated emails.

**Comment by rodrigoscoelho** [comment] 2019-11-19 18:39
Based on this page, the UID should not change.

https://www.limilabs.com/blog/unique-id-in-imap-protocol

**Comment by yurikuzn** [comment] 2019-11-19 18:46
There was an issue, after we updated mail parser library that ids were stored without `<>`.  You can check their message_id in database.

**Comment by yurikuzn** [comment] 2019-11-19 18:50
We don't rely on UID. We check message-id.

**Comment by rodrigoscoelho** [comment] 2019-11-19 19:17
Is this fixed now? When did you fix it?

Actually, the problem is that EspoCRM was not fetching new mails that
arrived on the same conversation (the same label on gmail). I have to
deselect the label, and select again.
That way, EspoCRM fetch the new arrived emails on that old conversation.

BUT, since 2 months (I guess), we are having problems with it fetching even
the old emails, again.
It is a mess.
Any way to fix it from here?

Thanks Yuri.

Em ter., 19 de nov. de 2019 às 15:50, Yuri Kuznetsov <
notifications@github.com> escreveu:

**Comment by yurikuzn** [comment] 2019-11-19 19:36
From 5.7.0, fixed in 5.7.6. Emails fetched when you were between 5.7.0 and 5.7.6 can be fetched twice if you re-initiate sync.

You need to check message_id of any two duplicate pairs.

**Comment by yurikuzn** [comment] 2019-11-19 19:37
Need to check message_id to make sure that this is that issue.

**Comment by rodrigoscoelho** [comment] 2019-11-19 19:39
I will start monitoring now, since I'm already on 5.7.7.

The problems are still happening because most of emails were downloaded
before 5.7.7. So, I will still have these problems probably.

Thanks

Em ter., 19 de nov. de 2019 às 16:37, Yuri Kuznetsov <
notifications@github.com> escreveu:

**Comment by yurikuzn** [comment] 2019-11-19 19:42
Messages imported between 5.7.0 and 5.7.6 have not correct ids. So you still can have duplicates of those messages created, even if you on 5.7.7 and later.

**Comment by yurikuzn** [comment] 2019-11-19 19:45
If you find out that it's caused by message-ids w/o `<` and `>` you can run sql query that will add them.

**Comment by rodrigoscoelho** [comment] 2019-11-19 19:56
Any clue of a query I can do? I'm not specialist of SQL.
I have clients of SQL, I can do it easily, but I don't know which query I
should use.

Thanks.

Em ter., 19 de nov. de 2019 às 16:45, Yuri Kuznetsov <
notifications@github.com> escreveu:

**Comment by rodrigoscoelho** [comment] 2019-11-19 20:01
Confirmed. Lot's of message Ids without <>

What should I do to fix it manually?


Em ter., 19 de nov. de 2019 às 16:56, rodrigoscoelho <
notifications@github.com> escreveu:

**Comment by rodrigoscoelho** [comment] 2019-11-19 20:04
By the way, we have the message_id_internal  without the "<>" too.

I suggest the next update to fix these automatically. Is it possible?
Thanks again.

Em ter., 19 de nov. de 2019 às 17:01, rodrigoscoelho <
notifications@github.com> escreveu:

**Comment by rodrigoscoelho** [comment] 2019-11-19 20:51
Should I try?

UPDATE email
SET
    message_id = '<'+ message_id + '>'
WHERE
    message_id NOT LIKE '<%'

Will this work? 😂

Em ter., 19 de nov. de 2019 às 17:04, rodrigoscoelho <
notifications@github.com> escreveu:

**Comment by yurikuzn** [comment] 2019-11-19 21:14
You need to use concatenate function.

But first check two duplicates, whether they have the same ids but one w/o `<>`.

**Comment by rodrigoscoelho** [comment] 2019-11-19 21:30
DONE as below:

UPDATE email SET message_id = CONCAT('<', message_id,'>') WHERE message_id
 NOT LIKE '<%'

Now I will monitor.

I'm still afraid the message_id_internal is without < as well. Will this
cause any problems?

Em ter., 19 de nov. de 2019 às 18:14, Yuri Kuznetsov <
notifications@github.com> escreveu:

**Comment by yurikuzn** [comment] 2019-11-20 06:13
Should not. Internal is not used.

**Comment by rodrigoscoelho** [comment] 2019-11-20 13:55
@yurikuzn ,
It just downloaded a duplicated email, again. Even after changing the message_id, yesterday.

Look the rows with duplicated info on database.

![image](https://user-images.githubusercontent.com/6912410/69244718-315d2d00-0b84-11ea-9565-ff73ec5a60c8.png)


"5dd304dceb1fc714d"	"Fwd: UFSC"	"1"	\N	"Aimsun Customer Service <info@aimsun.com>"	\N	"<A264F00F-F826-4C84-92E4-333EB022C744@aimsun.com>"	"<A264F00F-F826-4C84-92E4-333EB022C744@aimsun.com>-rodrigoscoelho@gmail.com"	"1"	"Archived"	"0"	"2019-09-18 07:41:53"	"2019-11-18 20:53:48"	"2019-11-18 21:39:46"	"0"	"57602f34049684443"
"5dd53784ccf0a4ead"	"Fwd: UFSC"	"0"	\N	"Aimsun Customer Service <info@aimsun.com>"	\N	"<A264F00F-F826-4C84-92E4-333EB022C744@aimsun.com>"	"<A264F00F-F826-4C84-92E4-333EB022C744@aimsun.com>-rodrigoscoelho@gmail.com"	"1"	"Archived"	"0"	"2019-09-18 07:41:53"	"2019-11-20 12:54:28"	"2019-11-20 12:54:28"	"0"	"57602f34049684443"

**Comment by yurikuzn** [comment] 2019-11-20 13:59
You set deleted after duplicate was created?

**Comment by yurikuzn** [comment] 2019-11-20 14:09
1. I have no clue how it can bypass duplicate check https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Mail/Importer.php#L166
2. Weird why the system imports emails that were already imported.

We never encountered both behaviors.

**Closed** 2022-11-01 15:51 UTC
