### ISSUE TITLE
Default Contacts in Meetings and Calls show Id instead of name

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2182] opened 2021-12-19 06:02 UTC
**Describe the bug**
When adding a meeting or call using the standard activities panel. If Contacts link is enabled on parent the contacts are added as default attendees however the Id is shown instead of the name

**To Reproduce**
Create a base plus entity
create a M:M link to contact
Add the contacts field to the detail view
Create a record and add some contacts
Create a meeting

**Expected behavior**
Name should be shown instead of Id

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/146666665-b6ebfd2e-85da-473e-92cc-aa308c16ca23.png)

**EspoCRM version**
7.0.9

**Additional context**
 'crm:views/record/panels/activities'
`            this.getCreateActivityAttributes(scope, data, function (attributes) {
                o.attributes = attributes; <-- this has both name and Id's set correctly
                this.createView('quickCreate', viewName, o , function (view) {
                    view.render();
                    view.notify(false);
                    this.listenToOnce(view, 'after:save', function () {
                        this.model.trigger('after:relate');
                        this.collection.fetch();
                        this.fetchHistory();
                    }, this);
                }, this);
            });
`

**Comment by yurikuzn** [comment] 2021-12-19 07:06
I could not reproduce. It could be you caused by your customization. I close it so far.

**Closed by yurikuzn** 2021-12-19 07:06 UTC

**Comment by boydle** [comment] 2021-12-19 07:21
I cant find anywhere is the default application to demo this however I am not sure its my customisation.

I have fixed it like this:

This view 'crm:views/record/panels/activities' has this code that creates 2 arrays.

                if (this.model.name != 'Account' && this.model.has('contactsIds')) {
                    attributes.contactsIds = this.model.get('contactsIds');
                    attributes.contactsNames = this.model.get('contactsNames');
                }

The code that sets the defaults in the modal appears to require the attributes.contactsNames array to be a has of id:name


			if (this.model.name != 'Account' && this.model.has('contactsIds')) {
				attributes.contactsIds = this.model.get('contactsIds');
				attributes.contactsNames = {};
				for (let index = 0; index < attributes.contactsIds.length; ++index) {
					attributes.contactsNames[this.model.get('contactsIds')[index]] = this.model.get('contactsNames')[index];	
				}
			}

The above code works for me.

**Comment by yurikuzn** [comment] 2021-12-19 07:41
> attributes.contactsNames array to be a has of id:name

It's the way how it's been always  working in espo. I'm pretty sure it's your customization changed the way how the value in the attribute `contactsNames` is formatted. 

On your screenshot it's seen that you has a customized link-multiple view. Please try to reproduce on an uncustomized instance first, it would save time.
