### ISSUE TITLE
Duplicate IDs in query results

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1504] opened 2019-11-11 00:18 UTC
When I run this code to check for squential duplicates in an entryPoint I get many hits.

```PHP
$leadRepository = $this->getEntityManager()->getRepository('Lead');
$list = $leadRepository->limit(0,100000)->find();
$previousId = '';
foreach ($list as $entity){   
   if (($previousId) == $entity->id) echo("DUPLICATE ID: $previousId\n");
   $previousId = $entity->id;
}
```
Output:
```
DUPLICATE ID: 5a143a290df89d275
DUPLICATE ID: 5a155d2142bd9d663
DUPLICATE ID: 5a1551be81d3d5fd3
DUPLICATE ID: 5a1548dfc4a69803f
DUPLICATE ID: 5a565ca624832e994
DUPLICATE ID: 5a565c9dd2f50ed33
DUPLICATE ID: 5a565c987441d1115
DUPLICATE ID: 5a565c8883c758c33
DUPLICATE ID: 5a565c7e0e0768e5d
DUPLICATE ID: 5a565c7651e56c4e6
DUPLICATE ID: 5a565c6bb47be1b63
DUPLICATE ID: 5a565c67e07f8bcc4
DUPLICATE ID: 5a565c654da98acb3
DUPLICATE ID: 5a565c6292a74ea75
DUPLICATE ID: 5a565c5e93887891b
DUPLICATE ID: 5a565c5a89412a1d0
DUPLICATE ID: 5a565c59538d55bf8
DUPLICATE ID: 5a565c3bcc4a299b9
DUPLICATE ID: 5a565c3b83da9dc14
DUPLICATE ID: 5a565c3aa605ea557
DUPLICATE ID: 5a565c39c22c57fde
DUPLICATE ID: 5a565c38e54881827
DUPLICATE ID: 5a565c38c69d7f72f
DUPLICATE ID: 5a565c38926d91cdd
DUPLICATE ID: 5a565c3877ece471f
DUPLICATE ID: 5a565c35f05576e73
DUPLICATE ID: 5a565c303f7bc0d0a
DUPLICATE ID: 5a565c2dce63ddd97
DUPLICATE ID: 5a565c1d2b5f9b2d4
```

I checked the database and those rows are not duplicated. Only in the results it seems.

I tried looking for all duplicates and this is the result....

```PHP

$leadRepository = $this->getEntityManager()->getRepository('Lead');
$list = $leadRepository->limit(0,100000)->find();
$previousIds = []; $duplicates = [];
foreach ($list as $entity){
   if (in_array($entity->id,$previousIds)) {echo("DUPLICATE ID: $entity->id\n");
   $duplicates []= $entity->id;}
   $previousIds []= $entity->id;
}

echo count($duplicates)." duplicate results found.";


```

Output:

```
DUPLICATE ID: 5a143a290df89d275
DUPLICATE ID: 5a155d2142bd9d663
DUPLICATE ID: 5a1551be81d3d5fd3
DUPLICATE ID: 5a1548dfc4a69803f
DUPLICATE ID: 5a565ca624832e994
DUPLICATE ID: 5a565c9dd2f50ed33
DUPLICATE ID: 5a565c987441d1115
DUPLICATE ID: 5a565c8883c758c33
DUPLICATE ID: 5a565c7e0e0768e5d
DUPLICATE ID: 5a565c7651e56c4e6
DUPLICATE ID: 5a565c6bb47be1b63
DUPLICATE ID: 5a565c67e07f8bcc4
DUPLICATE ID: 5a565c654da98acb3
DUPLICATE ID: 5a565c6292a74ea75
DUPLICATE ID: 5a565c5e93887891b
DUPLICATE ID: 5a565c5a89412a1d0
DUPLICATE ID: 5a565c59538d55bf8
DUPLICATE ID: 5a565c3bcc4a299b9
DUPLICATE ID: 5a565c3b83da9dc14
DUPLICATE ID: 5a565c3aa605ea557
DUPLICATE ID: 5a565c39c22c57fde
DUPLICATE ID: 5a565c38e54881827
DUPLICATE ID: 5a565c38c69d7f72f
DUPLICATE ID: 5a565c38926d91cdd
DUPLICATE ID: 5a565c3877ece471f
DUPLICATE ID: 5a565c35f05576e73
DUPLICATE ID: 5a565c303f7bc0d0a
DUPLICATE ID: 5a565c2dce63ddd97
DUPLICATE ID: 5a565c1d2b5f9b2d4
DUPLICATE ID: 5a565be3b505460e8
DUPLICATE ID: 5a565be2ae8af7ccd
DUPLICATE ID: 5a565be1776744cf0
DUPLICATE ID: 5a565bdccd4256aab
DUPLICATE ID: 5bb1cf9f067a3dc58
DUPLICATE ID: 5bbee212ddc5ccf21
DUPLICATE ID: 5bbee226d3920f42c
DUPLICATE ID: 5bc75292df1a48fa2
DUPLICATE ID: 5bc76ae467bc2b23a
DUPLICATE ID: 5bc89997cba73e7e7
DUPLICATE ID: 5bbdfb801c1d149c5
40 duplicate results found.
```

Sounds like a bug...

**Comment by yurikuzn** [comment] 2019-11-11 06:47
I can't believe it's a bug. Can you investigate deeply? You need to use DISTINCT if the query has hasMany joins. You didn't provided a content of $wc. I close it for now. I will re-open if there will be more info.

**Comment by yurikuzn** [comment] 2019-11-11 07:36
I run your script and got 0 duplicates on 50,000 records.

**Comment by beppe9000** [comment] 2019-11-11 12:36
Both $wc and $find_settings are intentionally null so the default is empty array for both.

What steps can I take to investigate this properly ?

**Comment by yurikuzn** [comment] 2019-11-11 13:15
Here https://github.com/espocrm/espocrm/blob/master/application/Espo/ORM/DB/Query/Base.php#L438

**Comment by beppe9000** [comment] 2019-11-11 13:59
Ok. BTW, can it be overridden in `custom` ?

**Comment by beppe9000** [comment] 2019-11-11 14:14
I've dumped the query:

`SELECT lead.id AS `id`, TRIM(CONCAT(IFNULL(lead.first_name, ''), ' ', IFNULL(lead.last_name, ''))) AS `name`, lead.deleted AS `deleted`, lead.salutation_name AS `salutationName`, lead.first_name AS `firstName`, lead.last_name AS `lastName`, lead.title AS `title`, lead.status AS `status`, lead.source AS `source`, lead.industry AS `industry`, lead.opportunity_amount AS `opportunityAmount`, lead.website AS `website`, lead.address_street AS `addressStreet`, lead.address_city AS `addressCity`, lead.address_state AS `addressState`, lead.address_country AS `addressCountry`, lead.address_postal_code AS `addressPostalCode`, emailAddresses.name AS `emailAddress`, phoneNumbers.name AS `phoneNumber`, lead.do_not_call AS `doNotCall`, lead.description AS `description`, lead.converted_at AS `convertedAt`, lead.created_at AS `createdAt`, lead.modified_at AS `modifiedAt`, lead.account_name AS `accountName`, lead.cluster AS `cluster`, lead.rating AS `rating`, lead.tipologia_cliente AS `tipologiaCliente`, lead.partita_i_v_a AS `partitaIVA`, lead.insegna AS `insegna`, lead.capitale_sociale AS `capitaleSociale`, lead.dipendenti AS `dipendenti`, lead.fatturato AS `fatturato`, lead.ruolo AS `ruolo`, lead.funzione AS `funzione`, lead.anno_costituzione AS `annoCostituzione`, lead.cliente_vodafone AS `clienteVodafone`, lead.codice_vodafone AS `codiceVodafone`, lead.lista_esclusi AS `listaEsclusi`, lead.copertura_g_e_a_fisso AS `coperturaGEAFisso`, lead.copertura_g_e_a_mobile AS `coperturaGEAMobile`, lead.nr_centrale AS `nrCentrale`, lead.distanza_centrale AS `distanzaCentrale`, lead.distanza_cabinet AS `distanzaCabinet`, cap.zona AS `zona`, cap.area AS `area`, cap.denominazione AS `capDenominazione`, lead.attivo AS `attivo`, lead.referente AS `referente`, centralitelefonica.nome_centrale AS `nomecentrale`, lead.nome_referente AS `nomeReferente`, lead.cognome_referente AS `cognomeReferente`, lead.note_referente AS `noteReferente`, lead.no_consenso_mail AS `noConsensoMail`, lead.telefono_referente AS `telefonoReferente`, lead.iva_valida AS `ivaValida`, lead.iva_attiva AS `ivaAttiva`, lead.altre_offerte AS `altreOfferte`, lead.categoria AS `categoria`, lead.is_confcommercio AS `isConfcommercio`, lead.last_crawl AS `lastCrawl`, lead.gea_error AS `geaError`, lead.gea_status AS `geaStatus`, lead.z_gea_fisso AS `zGeaFisso`, lead.z_gea_mobile AS `zGeaMobile`, lead.z_mail AS `zMail`, lead.z_phone_number AS `zPhoneNumber`, lead.tag AS `tag`, lead.iva_last_check AS `ivaLastCheck`, lead.last_call AS `lastCall`, lead.send_bot_mail AS `sendBotMail`, lead.nascosto AS `nascosto`, lead.url_pagine_gialle AS `urlPagineGialle`, lead.ii_url AS `iiUrl`, lead.ii_categoria AS `iiCategoria`, lead.numeri_di_telefono_validi AS `numeriDiTelefonoValidi`, lead.opportunity_amount_currency AS `opportunityAmountCurrency`, emailAddresses.opt_out AS `emailAddressIsOptedOut`, phoneNumbers.opt_out AS `phoneNumberIsOptedOut`, lead.opportunity_amount * opportunityAmountCurrencyRate.rate AS `opportunityAmountConverted`, lead.created_by_id AS `createdById`, TRIM(CONCAT(createdBy.first_name, ' ', createdBy.last_name)) AS `createdByName`, lead.modified_by_id AS `modifiedById`, TRIM(CONCAT(modifiedBy.first_name, ' ', modifiedBy.last_name)) AS `modifiedByName`, lead.assigned_user_id AS `assignedUserId`, TRIM(CONCAT(assignedUser.first_name, ' ', assignedUser.last_name)) AS `assignedUserName`, lead.campaign_id AS `campaignId`, lead.created_account_id AS `createdAccountId`, lead.created_contact_id AS `createdContactId`, lead.created_opportunity_id AS `createdOpportunityId`, lead.cap_id AS `capId`, cap.name AS `capName`, lead.centralitelefonica_id AS `centralitelefonicaId`, centralitelefonica.name AS `centralitelefonicaName`, lead.meeting_id AS `meetingId`, meeting.name AS `meetingName`, lead.telcall_assigned_user_id AS `telcallAssignedUserId`, TRIM(CONCAT(telcallAssignedUser.first_name, ' ', telcallAssignedUser.last_name)) AS `telcallAssignedUserName` FROM `lead` LEFT JOIN `user` AS `telcallAssignedUser` ON lead.telcall_assigned_user_id = telcallAssignedUser.id LEFT JOIN `meeting` AS `meeting` ON lead.meeting_id = meeting.id LEFT JOIN `centrali_telefoniche` AS `centralitelefonica` ON lead.centralitelefonica_id = centralitelefonica.id LEFT JOIN `c_a_p` AS `cap` ON lead.cap_id = cap.id LEFT JOIN `user` AS `assignedUser` ON lead.assigned_user_id = assignedUser.id LEFT JOIN `user` AS `modifiedBy` ON lead.modified_by_id = modifiedBy.id LEFT JOIN `user` AS `createdBy` ON lead.created_by_id = createdBy.id LEFT JOIN `entity_email_address` AS `emailAddressesMiddle` ON lead.id = emailAddressesMiddle.entity_id AND emailAddressesMiddle.deleted = '0' AND emailAddressesMiddle.primary = '1' AND emailAddressesMiddle.entity_type = 'Lead' LEFT JOIN `email_address` AS `emailAddresses` ON emailAddresses.id = emailAddressesMiddle.email_address_id AND emailAddresses.deleted = '0' LEFT JOIN `entity_phone_number` AS `phoneNumbersMiddle` ON lead.id = phoneNumbersMiddle.entity_id AND phoneNumbersMiddle.deleted = '0' AND phoneNumbersMiddle.primary = '1' AND phoneNumbersMiddle.entity_type = 'Lead' LEFT JOIN `phone_number` AS `phoneNumbers` ON phoneNumbers.id = phoneNumbersMiddle.phone_number_id AND phoneNumbers.deleted = '0' LEFT JOIN `currency` AS `opportunityAmountCurrencyRate` ON opportunityAmountCurrencyRate.id = lead.opportunity_amount_currency WHERE lead.deleted = '0' LIMIT 0, 20`

**Comment by bandtank** [comment] 2019-11-11 14:21
@beppe9000 What is the `??` operator from your query?

**Comment by beppe9000** [comment] 2019-11-11 14:24
equivalent of :

`$list = $leadRepository->where([ ])->limit(0,100000)->find([ ]);`

**Comment by yurikuzn** [comment] 2019-11-11 14:34
> be overridden in custom ?

I don't know if it's possible.

> What is the ?? operator from your query

https://wiki.php.net/rfc/isset_ternary

**Comment by yurikuzn** [comment] 2019-11-11 14:37
Must be duplicates in some joined tables. Try to find it and remove.

Or use `->distinct(true)`

**Comment by beppe9000** [comment] 2019-11-11 14:40
As a workaround I shall use distinct. Is it normal for duplicates to be in those tables?

**Comment by yurikuzn** [comment] 2019-11-11 17:24
It's not normal, usually you don't have them. Maybe something went wrong. First, you need to know where are duplicates. You can add all id columns from joined tables to SELECT statement. Then, on duplicate rows ids must be different, It will be the cause of the duplicate.

**Comment by beppe9000** [comment] 2019-11-14 09:55
The 9-th row is `phone_number`.id, so maybe the problem is there?
![image](https://user-images.githubusercontent.com/6625123/68823735-f004e300-0694-11ea-8ca4-958790911312.png)

**Closed** 2022-11-01 15:49 UTC
