### ISSUE TITLE
Compose Email: Address w/ plus sign added incorrectly

### ISSUE THREAD

**Issue by tonybyng** [espocrm/espocrm#1222] opened 2019-02-02 11:53 UTC
Google (and possibly others) allow email addresses to have a + within the email (which i gather is allowed in the RFC) that you can use to give yourself more email addresses that relate to your own account. i.e. tonyb+espocrm@example.com. 

Within cases (and possibly emails in general), if I send a case email and select a contact with the above style address it strips off the bit prior to the + and so will end up sending the email to espocrm@example.com instead.  In fact it shows on screen that its already stripped off the + and prior after you've selected the user.

**Comment by yurikuzn** [comment] 2019-02-02 15:16
Hi,

I can't reproduce. I tried to send an email to 'tonyb+espocrm@example.com' and haven't noticed that address was stripped anywhere. Could you describe steps to reproduce more detail please.

**Comment by tonybyng** [comment] 2019-02-02 15:35
Hi

Thanks for the reply. I go to an existing case, I click onto the Activities ellipsis and choose Compose Email and in the To box I start typing tonyb and I see "Tony Byng <tonyb+test@example.com>" and I click on it and on screen it shows "Tony Byng » test@example.com" and it sends to that address too (i.e. its not just a display issue)

The contact data came in from an API transfer but Ive just created a contact in the system and it happens with that too. This is in Chrome on Linux and EspoCRM 5.5.6

Thanks

T

**Comment by yurikuzn** [comment] 2019-02-02 15:40
Problem seems to be with autocomplete only.

**Comment by tonybyng** [comment] 2019-02-02 16:50
Hi
Thanks for being able to recreate although for your information I dont think its auto complete only - have literally just typed in t+b@example.com without having that email in the list so it wasn't via an autocomplete and it ended up as b@example.com

**Comment by yurikuzn** [comment] 2019-02-02 17:06
Thanks for reporting. Will be fixed in the next maintenance release.

**Comment by yurikuzn** [comment] 2019-02-04 08:50
https://github.com/espocrm/espocrm/commit/2e38270083e7abd434a990a4206aa5ce6f5ccd19

**Closed by yurikuzn** 2019-02-04 08:50 UTC
Labels: bug

**Comment by bandtank** [comment] 2019-02-04 11:07
The updated regex is a little confusing to me. Why does the expression include `d\+”` instead of only `\+`?

**Comment by yurikuzn** [comment] 2019-02-04 11:53
I get error when use `\+`. Could you suggest me what to use for plus sign?

**Comment by yurikuzn** [comment] 2019-02-04 12:06
I found the problem.

**Comment by yurikuzn** [comment] 2019-02-04 12:08
https://github.com/espocrm/espocrm/commit/d81d66ea5d40a212257b9f4a5a89f96b67b0877c

**Comment by bandtank** [comment] 2019-02-04 12:08
There are a few errors in the regex. With this one in particular, it’s due to the - not being escaped, so it’s acting like a range instead of a literal -. The same problem exists in other parts of the regex as well. However, the validation rules in both parts of the regex aren’t right. I am not in front of a computer right now, but I’ll send you an update in a few hours with a regex that will check the full range of valid email addresses.

**Comment by tonybyng** [comment] 2019-02-04 12:11
Have to admit I wondered about the d but also when I checked the RFC for valid characters I thought I saw more than were in the regex but hadn't managed to check since, and whilst my regex abilities are okay, I wouldn't feel confident saying "you need to change it to this" ;-)

**Comment by bandtank** [comment] 2019-02-04 14:20
The current regex is too permissive. Here are some examples that are matched by the regex incorrectly:

```
test_@test.com.
test.@_._
"@_.-
"@_._._.
```

The rules are extremely hard to implement, so we're not likely to every get a completely correct regex test. There are a few simple errors that can be caught, though, like trailing underscores. Here's the recommended regex from [HTML5 on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#Validation):
```
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}
[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
```

However, that doesn't take into account unicode characters. Given that EspoCRM is used all over the world, not matching on unicode characters seems like a potential issue. There are ways to handle that without being overly restrictive while still catching most common errors, e.g.:
```
^\S+@\S+$
[^@]+@[^@]+\.[^@]+
```

The RFC2822 shown above from MDN is more official, but also a lot more complicated. I think the idea in EspoCRM is to match a known address and, really, the email provider is the ultimate validity test.

If you aren't aware of [this site](https://regex101.com/), it can be a big help.

**Comment by yurikuzn** [comment] 2019-02-04 15:02
We have good regexp for email fields: https://github.com/espocrm/espocrm/blob/master/client/src/views/fields/email.js#L49

**Comment by yurikuzn** [comment] 2019-02-05 09:22
I added an additional server side validation https://github.com/espocrm/espocrm/commit/f99cac5d4c95d75b6f85dba129e9f23e36c027ae
