### ISSUE TITLE
Badly formatted currency values raises 500 error in import step2

### ISSUE THREAD

**Issue by AlexxxH** [espocrm/espocrm#2901] opened 2023-11-16 11:21 UTC
**Describe the bug**
When importing data for an entity which contains a currency field, badly formatted currency values (e.g. strings containing commas such as "3,100") in the imported data raise an "Error 500" mesage on the import step 2 page. It is not possible to continue past this step.
Instead, badly formatted currency values should behave the same as other badly formatted data types (e.g. dates, floats, etc), and be shown in the "Errors" panel on the import detail page.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Create an entity with a currency field
2. Create a dataset with a column for the currency field. Add badly formatted values in the column, e.g. strings with commas such as "3,100"
3. In EspoCRM go to Import -> upload the CSV file -> Next
4. In Import step2, match the currency entity field to the CSV currency column name
5. Click "Run Import" - see red "Error 500" notification appear

**Expected behavior**
Badly formatted currency values should behave the same as other badly formatted fields (e.g. floats, dates, etc), i.e. they should not stop the import, and should be displayed in the "Errors" panel on the import detail page.

**EspoCRM version**
EspoCRM version: 8.0.2

**Comment by yurikuzn** [comment] 2023-11-16 12:01
Could not reproduce.

![image](https://github.com/espocrm/espocrm/assets/1006792/9d721573-e5c1-4562-96b3-36eed50531c2)

What is in the log?

**Comment by AlexxxH** [comment] 2023-11-16 13:52
I created a currency field called "Transfer Value". In the import step 2, when matching up columns, it gives the options "Transfer Value" and "TransferValue (Currency)". The 500 error is only when I select "Transfer Value" instead of "TransferValue (Currency)". I guess this is what you're meant to do? In that case, perhaps the other option (in my case "Transfer Value") should be removed from the options dropdown in import step 2?

**Comment by yurikuzn** [comment] 2023-11-16 15:06
The key thing to reproduce was checking "Decimal".

**Comment by yurikuzn** [comment] 2023-11-16 15:46
Fixed by existing on the first validation failure per field. Drawback: if multiple validations failing per field, only the first will be logged.

https://github.com/espocrm/espocrm/commit/70f15a7cbd929f28f2e28ef4fd3baf90e267ab9a

**Closed by yurikuzn** 2023-11-16 15:46 UTC

**Comment by AlexxxH** [comment] 2023-11-16 18:47
Thanks for fixing!

**Comment by yurikuzn** [comment] 2023-11-16 19:56
I also added a logic that strips thousands separator when importing currency, float and int fields. In v8.1.
